[package]
name = "auto-sigmar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouce = "0.2.1"
scrap = "0.5.0"
image = "0.23.14"
